using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wolf.Vecc.Model.ResultModel
{
    public class CalculationResultData
    {
        public string p_odo_cru { get; set; }
        public string NO_abn_CO2 { get; set; }
        public string NO_abn_qvf { get; set; }
        public string Speed_c4 { get; set; }
        public string BSCO_avg { get; set; }
        public string NO_SJ_r { get; set; }
        public string NOx_v_avg { get; set; }
        public string NO_abn_vecu { get; set; }
        public string p_l120 { get; set; }
        public string stringWeight_c3 { get; set; }
        public string Weight_c2 { get; set; }
        public string Weight_c1 { get; set; }
        public string duration_stable_l2i5m { get; set; }
        public string Weight_c7 { get; set; }
        public string Weight_c6 { get; set; }
        public string p_odo_m { get; set; }
        public string Weight_c4 { get; set; }
        public string NOx_min { get; set; }
        public string Weight_c9 { get; set; }
        public string Weight_c8 { get; set; }
        public string V_avg_trips { get; set; }
        public string BSCO2_avg { get; set; }
        public string duration_dec { get; set; }
        public string m_slope { get; set; }
        public string NO_abn_CO { get; set; }
        public string BSCO_p95 { get; set; }
        public string p_odo_r { get; set; }
        public string t_delay_1t4 { get; set; }
        public string t_delay_1t3 { get; set; }
        public string t_delay_1t2 { get; set; }
        public string p_odo_u { get; set; }
        public string duration_trips { get; set; }
        public string Speed_c5 { get; set; }
        public string HC_v_min { get; set; }
        public string Speed_c7 { get; set; }
        public string Speed_c6 { get; set; }
        public string Speed_c1 { get; set; }
        public string PN_v_max { get; set; }
        public string Speed_c2 { get; set; }
        public string p_l150 { get; set; }
        public string p_time_cru { get; set; }
        public string Speed_c9 { get; set; }
        public string Speed_c8 { get; set; }
        public string BSNOx_max { get; set; }
        public string inx_Motorway_d { get; set; }
        public string BSCO2_std { get; set; }
        public string p_l90 { get; set; }
        public string CO2_v_max { get; set; }
        public string NO_abn_Pair { get; set; }
        public string p_l10 { get; set; }
        public string CO_v_avg { get; set; }
        public string odo_trips { get; set; }
        public string Speed_c10 { get; set; }
        public string NO_abn_Tair { get; set; }
        public string inx_Rural_d { get; set; }
        public string p_BSNOx_vWDs { get; set; }
        public string BSCO_std { get; set; }
        public string BSCO2_max { get; set; }
        public string P_air_avg { get; set; }
        public string NO_nox_lt500 { get; set; }
        public string inx_Rural_s { get; set; }
        public string HC_v_max { get; set; }
        public string t_delay_4t2 { get; set; }
        public string t_delay_4t3 { get; set; }
        public string t_delay_4t1 { get; set; }
        public string p_l100 { get; set; }
        public string NO_c14 { get; set; }
        public string Alt_p_cusum { get; set; }
        public string NO_c12 { get; set; }
        public string NO_c13 { get; set; }
        public string NO_c10 { get; set; }
        public string NO_c11 { get; set; }
        public string NO_abn_tclnt { get; set; }
        public string Torque_c11 { get; set; }
        public string r2_qmfuel { get; set; }
        public string CO_v_max { get; set; }
        public string odo_vecu { get; set; }
        public string NO_abn_spd { get; set; }
        public string time_test { get; set; }
        public string power_max { get; set; }
        public string Temp_start_res_PF { get; set; }
        public string p_l20 { get; set; }
        public string t_delay_3t2 { get; set; }
        public string BSCO_min { get; set; }
        public string duration_u { get; set; }
        public string odo_r { get; set; }
        public string odo_cru { get; set; }
        public string V_avg_r { get; set; }
        public string inx_Motorway_s { get; set; }
        public string inx_Urban_d { get; set; }
        public string t_delay_3t4 { get; set; }
        public string p_l110 { get; set; }
        public string t_delay_3t1 { get; set; }
        public string p_BSCO_vWDs { get; set; }
        public string Alt_min { get; set; }
        public string NO_c5 { get; set; }
        public string duration_coldstart { get; set; }
        public string odo_test { get; set; }
        public string inx_Urban_s { get; set; }
        public string Weight_c11 { get; set; }
        public string odo_dec { get; set; }
        public string BSHC_min { get; set; }
        public string NO_c8 { get; set; }
        public string NO_c9 { get; set; }
        public string NOx_p95 { get; set; }
        public string time_normaltest_s0 { get; set; }
        public string NO_c4 { get; set; }
        public string Alt_max { get; set; }
        public string NO_c7 { get; set; }
        public string NO_c1 { get; set; }
        public string NO_c2 { get; set; }
        public string NO_c3 { get; set; }
        public string duration_test { get; set; }
        public string work_times { get; set; }
        public string BSHC_p95 { get; set; }
        public string BSHC_std { get; set; }
        public string odo_u { get; set; }
        public string V_avg_m { get; set; }
        public string odo_m { get; set; }
        public string mass_curb { get; set; }
        public string p_time_r { get; set; }
        public string p_time_u { get; set; }
        public string BSPN_min { get; set; }
        public string duration_r { get; set; }
        public string PN_v_avg { get; set; }
        public string odo_vgps { get; set; }
        public string NO_abn_THC { get; set; }
        public string Q100_coldstart { get; set; }
        public string Speed_c14 { get; set; }
        public string V_avg_u { get; set; }
        public string p_l80 { get; set; }
        public string NOx_v_max { get; set; }
        public string p_time_m { get; set; }
        public string duration_acc { get; set; }
        public string BSFC_std { get; set; }
        public string BSFC_min { get; set; }
        public string BSNOx_min { get; set; }
        public string T_air_test_s0 { get; set; }
        public string p_time_dec { get; set; }
        public string p_pow_f { get; set; }
        public string NO_SJ_m { get; set; }
        public string BSNOx_avg { get; set; }
        public string p_l60 { get; set; }
        public string BSHC_p90 { get; set; }
        public string delt_Alt_d2s { get; set; }
        public string rel_err_odo { get; set; }
        public string NO_SJ_u { get; set; }
        public string Torque_c8 { get; set; }
        public string pems_manufacturer { get; set; }
        public string T_clnt_test_s0 { get; set; }
        public string NOx_v_min { get; set; }
        public string Speed_c13 { get; set; }
        public string Torque_c1 { get; set; }
        public string Torque_c3 { get; set; }
        public string Torque_c2 { get; set; }
        public string Torque_c5 { get; set; }
        public string Torque_c4 { get; set; }
        public string Torque_c7 { get; set; }
        public string Torque_c6 { get; set; }
        public string Emission_res_PF { get; set; }
        public string BSFC_max { get; set; }
        public string BSCO_max { get; set; }
        public string Trips_res_PF { get; set; }
        public string NO_valid_wWDs { get; set; }
        public string CO_v_min { get; set; }
        public string BSHC_avg { get; set; }
        public string odo_acc { get; set; }
        public string NOx_max { get; set; }
        public string p_l50 { get; set; }
        public string mass_max { get; set; }
        public string Q100_m { get; set; }
        public string p_valid_wWDs { get; set; }
        public string NO_abn_NO { get; set; }
        public string NO_abn_vgps { get; set; }
        public string Date_test { get; set; }
        public string BSCO_p90 { get; set; }
        public string BSPN_p95 { get; set; }
        public string Alt_res_PF { get; set; }
        public string BSPN_p90 { get; set; }
        public string CO2_v_min { get; set; }
        public string p_l70 { get; set; }
        public string Weight_c13 { get; set; }
        public string Weight_c12 { get; set; }
        public string Work_cyc_t { get; set; }
        public string Weight_c10 { get; set; }
        public string NO_c6 { get; set; }
        public string NOx_p90 { get; set; }
        public string Weight_c14 { get; set; }
        public string t_delay_2t4 { get; set; }
        public string vehicle_class { get; set; }
        public string NO_abn_ALT { get; set; }
        public string t_delay_2t1 { get; set; }
        public string p_odo_acc { get; set; }
        public string t_delay_2t3 { get; set; }
        public string Q100_u { get; set; }
        public string p_NOx_ls500 { get; set; }
        public string BSCO2_min { get; set; }
        public string HC_v_avg { get; set; }
        public string Q100_r { get; set; }
        public string p_l40 { get; set; }
        public string NOx_avg { get; set; }
        public string PN_v_min { get; set; }
        public string CO2_v_avg { get; set; }
        public string r_payload { get; set; }
        public string BSFC_p90 { get; set; }
        public string BSFC_p95 { get; set; }
        public string Speed_c3 { get; set; }
        public string BSFC_avg { get; set; }
        public string NOx_std { get; set; }
        public string p_time_acc { get; set; }
        public string odo_idle { get; set; }
        public string p_odo_idle { get; set; }
        public string BSPN_avg { get; set; }
        public string NO_SJ_trips { get; set; }
        public string BSPN_max { get; set; }
        public string NO_abn_NO2 { get; set; }
        public string duration_m { get; set; }
        public string BSCO2_p90 { get; set; }
        public string vehicle_model { get; set; }
        public string Weight_c5 { get; set; }
        public string NO_abn_qme { get; set; }
        public string duration_cru { get; set; }
        public string NO_wWDs { get; set; }
        public string Torque_c9 { get; set; }
        public string BSHC_max { get; set; }
        public string BSPN_std { get; set; }
        public string p_BSPN_vWDs { get; set; }
        public string BSNOx_std { get; set; }
        public string Speed_c11 { get; set; }
        public string p_time_idle { get; set; }
        public string Speed_c12 { get; set; }
        public string NO_abn_PN { get; set; }
        public string T_air_avg { get; set; }
        public string p_l30 { get; set; }
        public string Torque_c10 { get; set; }
        public string Torque_c13 { get; set; }
        public string Torque_c12 { get; set; }
        public string Torque_c14 { get; set; }
        public string p_odo_dec { get; set; }
        public string BSCO2_p95 { get; set; }
        public string BSNOx_p95 { get; set; }
        public string duration_clntb70 { get; set; }
        public string duration_idle { get; set; }
        public string NO_abn_NOx { get; set; }
        public string p_l1 { get; set; }
        public string BSNOx_p90 { get; set; }
        public string Q100_trips { get; set; }
        public string odo_coldstart { get; set; }
    }
}
